---

#
# NOTE: There's a Grafana alert set up for the reliability of this pipeline:
#
#       https://grafana.monitoring.cd.gds-reliability.engineering/d/1go_x9sMz/concourse-alerts?orgId=1
#
#       This will alert #govuk-2ndline if this job's reliability drops below
#       70% over the course of a day. It relies on the name of the pipeline
#       (operations) and the task (mirror-repos). The #re-autom8 team can give
#       you edit access to Grafana if you need to update the alert.
#

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

resources:
  - name: mirror-repos-git
    type: git
    source:
      uri: https://github.com/alphagov/govuk-repo-mirror.git
      branch: master

  - name: every-two-hours-7am-to-9pm
    type: time
    source:
      interval: 2h
      start: 7:00 AM
      stop: 9:00 PM

  - name: govuk-2ndline-slack
    type: slack-notification
    source:
      url: ((govuk_platform_health_slack_webhook_url))


jobs:
  - name: update-pipeline
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: operations
        file: git-master/concourse.yml

  - name: mirror-repos
    serial: true
    plan:
      - get: mirror-repos-git
        trigger: true

      - get: every-two-hours-7am-to-9pm
        trigger: true

      - task: get-repos
        timeout: 90m
        config:
          params:
            ENSURE_DEFAULT_BRANCH: true
            GITHUB_ACCESS_TOKEN: ((mirror_repos_github_api_token))
            ROLE_ARN: arn:aws:iam::((govuk_tools_account_id)):role/govuk-concourse-codecommit-role
            GIT_SSH_PRIVATE_KEY: ((git_ssh_private_key))
            AWS_CODECOMMIT_USER_ID: ((aws_codecommit_user_id))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.6.6
              username: ((docker_hub_username))
              password: ((docker_hub_authtoken))
          inputs:
            - name: mirror-repos-git
          run:
            dir: mirror-repos-git
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail

                apt-get update  --yes
                apt-get install --yes awscli

                echo "$GIT_SSH_PRIVATE_KEY" \
                | base64 --decode           \
                | openssl rsa -inform DER   \
                > /tmp/git_ssh_key

                chmod 400 /tmp/git_ssh_key
                export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i /tmp/git_ssh_key"

                bundle install
                ./mirror_repos

